### ISSUE TITLE
[BUG]: Make the UI of Rock paper scissor more attractive

### ISSUE THREAD

**Issue by p2peek** [ShivamVashisth28/2-player-game#12]
1. Make Two different sections for user as well as CPU (can put left side of screen for user and right side for the CPU)
2. Use different button images for selectin of rock paper scissor
3. Use the score card in between of the screen and also the refresh button

# The UI should look some what like this 
![image](https://github.com/user-attachments/assets/a20d944b-16a8-4f5e-943b-31af7837a8b9)

**Comment by hectorDB01** [comment]
bro, could i try this ? i wanna help u
